system-load-alarm:
  enabled: true
  # cpu core count * %80 to trigger alarm by default
  limit-multiplier: 0.8
  # sends what creates the load into alarm message
  top-processes:
    enabled: true
    processes: 10

ram-usage-alarm:
  enabled: true
  # %90 to trigger alarm by default
  limit: 90
  # sends what creates the ram usage into alarm message
  top-processes:
    enabled: true
    processes: 10

disk-usage-alarm:
  enabled: true
  # This alarm limit is for individual partitions, because different devices can be mounted on different OS parts.
  # %90 to trigger alarm by default
  limit: 90

version-alarm:
  enabled: true
  # Each time any supported software updates its version, an Redmine news will be sent.
